language: cpp

cache:
- apt
- ccache

before_install:
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- echo "deb https://dl.bintray.com/laarid/main stretch main" | sudo tee /etc/apt/sources.list.d/bintray.list
- sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 379CE192D401AB61
- sudo apt-get update -qq

install:
- sudo apt-get install -qq devscripts equivs gcc-4.8 g++-4.8
- sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
- mk-build-deps -i -s sudo
- sudo apt-get install libunwind-dev libandroid-bionic0-dev

script:
- env
- debuild --preserve-env --preserve-envvar PATH -i -us -uc -b
